server:
  port: 9093
spring:
  data:
    mongodb:
      username: shipan
      password: 19980223
      host: localhost
      port: 27017
      database: cdb_customer
      authentication-database: admin


# Act as a eureka-client and connect to eureka(discovery)server:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9092/eureka/  # Corrected port to 9092
  register-with-eureka: true
  fetch-registry: true  # e.g. customer-service retrieves the list of services registered with Eureka, including order-service.
