services:
  mysql:
    image: mysql:8.0.33
    container_name: e_commerce_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 19980223
    volumes:
      - '/Users/shipanliu/tmp/tmp/a.cnf:/etc/mysql/my.cnf' # Always teh same config file
    ports:
      - 3309:3306
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: e_commerce_mongodb_container
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: shipan
      MONGO_INITDB_ROOT_PASSWORD: 19980223


  mail-dev:
    container_name: e_commerce_mail_dev
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - 1080:1080 # Exposes the Maildev web interface.
      - 1025:1025 # Exposes the SMTP service for testing email delivery.


networks:
  microservices-net:
    driver: bridge

volumes:
  mysql:
  mongo:






















































































































































































































































































































































































