server:
  port: 9092

spring:
  application:
    name: discovery-service
  config:
    # Act as a config-client tells the application to import configuration properties from the Spring Cloud Config Server at http://localhost:9091
    import: optional:configserver:http://localhost:9091





