spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:9091

  datasource:
    url: jdbc:mysql://localhost:3309/cdb_product  # Replace with your MySQL database URL
    username: shipan                               # Replace with your MySQL username
    password: 19980223


server:
  port: 9094



