spring:
  datasource:
    url: jdbc:mysql://localhost:3309/cdb_product
    username: shipan
    password: 19980223

  jpa:
    hibernate:
      ddl-auto: none # # Let Flyway manage schema creation and modifications entirely
    database: mysql

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # Instructs Flyway to treat the current state of the database as the baseline.It prevents Flyway from trying to reapply previous migrations by marking the baseline version as applied
    baseline-description: "init" # It prevents Flyway from trying to reapply previous migrations by marking the baseline version as applied
    baseline-version: 0 # Flyway will consider this version as the starting point, meaning it will not attempt to run migrations prior to this version
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
